name: Angular app
on:

  schedule:

    - cron: '*/2 * * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: App Service Web App Build Action
      uses: qianz2/appservice-build-test@master
